openapi: "3.1.0"
info:
  title: RoboTutor Chat API
  version: "1.0.0"
  description: FastAPI backend for the Physical AI textbook chatbot

servers:
  - url: http://localhost:8000
    description: Local development
  - url: https://api.example.com
    description: Production (TBD)

paths:
  /api/v1/chat:
    post:
      operationId: sendMessage
      summary: Send a chat message and receive a streamed response
      description: |
        Accepts a user message, optionally within an existing session.
        Supports "normal" mode (full-book vector retrieval) and
        "selected_text_only" mode (answer from provided text only).
        Returns Server-Sent Events (SSE) stream.
      tags: [chat]
      security:
        - BearerAuth: []
        - {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatRequest"
      responses:
        "200":
          description: SSE stream of response tokens
          content:
            text/event-stream:
              schema:
                $ref: "#/components/schemas/SSEStream"
        "400":
          $ref: "#/components/responses/BadRequest"
        "429":
          $ref: "#/components/responses/RateLimited"
        "500":
          $ref: "#/components/responses/InternalError"

  /api/v1/sessions:
    get:
      operationId: listSessions
      summary: List user's chat sessions
      tags: [sessions]
      security:
        - BearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        "200":
          description: List of sessions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionList"

  /api/v1/sessions/{session_id}/messages:
    get:
      operationId: getSessionMessages
      summary: Get all messages in a session
      tags: [sessions]
      security:
        - BearerAuth: []
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Message history
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageList"
        "404":
          $ref: "#/components/responses/NotFound"

  /api/v1/health:
    get:
      operationId: healthCheck
      summary: Check backend and dependency health
      tags: [operations]
      responses:
        "200":
          description: All systems healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "503":
          description: One or more dependencies degraded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Optional user token. Omit for anonymous access.

  schemas:
    ChatRequest:
      type: object
      required: [message]
      properties:
        message:
          type: string
          minLength: 1
          maxLength: 4000
          description: The user's question
        session_id:
          type: string
          format: uuid
          nullable: true
          description: Existing session ID. Omit to create a new session.
        mode:
          type: string
          enum: [normal, selected_text_only]
          default: normal
          description: Retrieval mode
        selected_text:
          type: string
          maxLength: 10000
          nullable: true
          description: Required when mode is selected_text_only
        source_doc_path:
          type: string
          nullable: true
          description: Document path for selected text context
        source_section:
          type: string
          nullable: true
          description: Section heading for selected text context
        filters:
          $ref: "#/components/schemas/QueryFilters"
          nullable: true

    QueryFilters:
      type: object
      properties:
        modules:
          type: array
          items:
            type: string
          nullable: true
        chapters:
          type: array
          items:
            type: string
          nullable: true
        content_types:
          type: array
          items:
            type: string
          nullable: true
        tags:
          type: array
          items:
            type: string
          nullable: true
        top_k:
          type: integer
          default: 5
          minimum: 1
          maximum: 20

    SSEStream:
      description: |
        Server-Sent Events stream with the following event types:
        - `token`: Partial response content
        - `done`: Final event with message metadata
        - `error`: Error event
      type: object

    TokenEvent:
      type: object
      properties:
        content:
          type: string
          description: Partial response text

    DoneEvent:
      type: object
      properties:
        message_id:
          type: string
          format: uuid
        session_id:
          type: string
          format: uuid
        citations:
          type: array
          items:
            $ref: "#/components/schemas/Citation"

    Citation:
      type: object
      properties:
        title:
          type: string
        section:
          type: string
        url:
          type: string
        module:
          type: string
        chapter:
          type: string

    SessionList:
      type: object
      properties:
        sessions:
          type: array
          items:
            $ref: "#/components/schemas/SessionSummary"
        total:
          type: integer

    SessionSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        message_count:
          type: integer
        last_activity:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time

    MessageList:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/MessageResponse"
        session_id:
          type: string
          format: uuid

    MessageResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        role:
          type: string
          enum: [user, assistant]
        content:
          type: string
        retrieval_mode:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [healthy, degraded]
        components:
          type: object
          properties:
            database:
              type: string
              enum: [ok, error]
            vector_store:
              type: string
              enum: [ok, error]
        timestamp:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    RateLimited:
      description: Rate limit exceeded
      headers:
        Retry-After:
          schema:
            type: integer
          description: Seconds until rate limit resets
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
